# Generated by Django 5.0 on 2023-12-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Узел отказа')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
            },
        ),
        migrations.CreateModel(
            name='DrivingAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель ведущего моста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель двигателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель техники')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Вид ТО')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='RecoverMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Способ восстановления')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название сервисной компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
            },
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель управляемого моста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Модель трансмиссии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.TextField(unique=True, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.TextField(verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.TextField(verbose_name='Зав. № трансмиссии')),
                ('driving_axle_serial_number', models.TextField(verbose_name='Зав. № ведущего моста')),
                ('steering_axle_serial_number', models.TextField(verbose_name='Зав. № управляемого моста')),
                ('contract', models.TextField(verbose_name='Договор поставки №, дата')),
                ('from_factory_shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('additional_options', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.TextField(verbose_name='Клиент')),
                ('driving_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.drivingaxlemodel', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.enginemodel', verbose_name='Модель двигателя')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.machinemodel', verbose_name='Модель техники')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.servicecompany', verbose_name='Сервисная компания')),
                ('steering_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.steeringaxlemodel', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.transmissionmodel', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'ordering': ['-from_factory_shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('order_number', models.TextField(verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.machine', verbose_name='Зав. № машины')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.maintenancetype', verbose_name='Вид ТО')),
                ('maintenance_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.FloatField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('used_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('recover_date', models.DateField(verbose_name='Дата восстановления')),
                ('breakdown_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.breakdownunit', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.machine', verbose_name='Зав. № машины')),
                ('recover_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.recovermethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламации',
                'ordering': ['-failure_date'],
            },
        ),
    ]
