from django.urls import path
from .views import *

urlpatterns = [
    path("", SearchMachines.as_view(), name="search"),
    path("machines/", machine_by_user, name="machine"),
    path("maintenance/", MaintenanceListView.as_view(), name="maintenance"),

    path("machineadd", MachineCreateView.as_view(), name="machine_create"),
    path("addmaintenance", MaintenanceCreateView.as_view(), name="maintenance_create"),
    path("claimadd", ClaimCreateView.as_view(), name="claim_create"),
    path("<int:pk>/medit", MachineUpdateView.as_view(), name="machine_update"),
    path("<int:pk>/tedit", MaintenanceUpdateView.as_view(), name="maintenance_update"),
    path("<int:pk>/cedit", ClaimUpdateView.as_view(), name="claim_update"),
    path("claim/", ClaimListView.as_view(), name="claims"),
    path("maintenance/<int:maintenance_id>/", maintenance_detail, name="maintenance_detail"),
    path("claim/<int:claim_id>/", claim_detail, name="claim_detail"),
    path("machine/<int:machine_id>/", machine_detail, name="machine_detail"),
    path("deletemachine/<int:pk>/", MachineDeleteView.as_view(), name="machine_delete"),
    path("deletemaintenance/<int:pk>/", MaintenanceDeleteView.as_view(), name="maintenance_delete"),
    path("deleteсo/<int:pk>/", ClaimDeleteView.as_view(), name="claim_delete"),
    path("claimlist/<int:machine_id>/", machine_claim_list, name="claim_list"),
    path("maintenancelist/<int:machine_id>/", machine_maintenance_list, name="maintenance_list"),

    path("servicecompany/", ServiceCompanyListView.as_view(), name="servicecompany_list"),
    path("machinemodel/", MachineModelListView.as_view(), name="machinemodel"),
    path("enginemodel/", EngineModelListView.as_view(), name="enginemodel"),
    path("transmissionmodel/", TransmissionModelListView.as_view(), name="transmissionmodel"),
    path("daxlemodel/", DrivingAxleModelListView.as_view(), name="daxlemodel"),
    path('saxlemodel/', SteeringAxleModelListView.as_view(), name='saxlemodel'),
    path('maintenancetype/', MaintenanceTypeListView.as_view(), name='maintenancetype_list'),
    path('breakdownunit/', BreakdownUnitListView.as_view(), name='breakdownunit'),
    path('recovermethod/', RecoverMethodListView.as_view(), name='recovermethod'),

    path('create_servicecompany/', ServiceCompanyCreateView.as_view(), name='create_servicecompany'),
    path('create_machinemodel/', MachineModelCreateView.as_view(), name='create_machinemodel'),
    path('create_enginemodel/', EngineModelCreateView.as_view(), name='create_enginemodel'),
    path('create_transmissionmodel/', TransmissionModelCreateView.as_view(), name='create_transmissionmodel'),
    path('create_daxlemodel/', DrivingAxleModelCreateView.as_view(), name='create_daxlemodel'),
    path('create_saxlemodel/', SteeringAxleModelCreateView.as_view(), name='create_saxlemodel'),
    path('create_maintenancetype/', MaintenanceTypeCreateView.as_view(), name='create_maintenancetype'),
    path('create_breakdownunit/', BreakdownUnitCreateView.as_view(), name='create_breakdownunit'),
    path('create_recovermethod/', RecoverMethodCreateView.as_view(), name='create_recovermethod'),

    path('delete_servicecompany/<int:pk>/', ServiceCompanyDeleteView.as_view(), name='delete_servicecompany'),
    path('delete_machinemodel/<int:pk>/', MachineModelDeleteView.as_view(), name='delete_machinemodel'),
    path('delete_enginemodel/<int:pk>/', EngineModelDeleteView.as_view(), name='delete_enginemodel'),
    path('delete_transmissionmodel/<int:pk>/', TransmissionModelDeleteView.as_view(), name='delete_transmissionmodel'),
    path('delete_daxlemodel/<int:pk>/', DrivingAxleModelDeleteView.as_view(), name='delete_daxlemodel'),
    path('delete_saxlemodel/<int:pk>/', SteeringAxleModelDeleteView.as_view(), name='delete_saxlemodel'),
    path('delete_maintenancetype/<int:pk>/', MaintenanceTypeDeleteView.as_view(), name='delete_maintenancetype'),
    path('delete_breakdownunit/<int:pk>/', BreakdownUnitDeleteView.as_view(), name='delete_breakdownunit'),
    path('delete_recovermethod/<int:pk>/', RecoverMethodDeleteView.as_view(), name='delete_recovermethod'),

    path('edit_servicecompany/<int:pk>/', ServiceCompanyUpdateView.as_view(), name='edit_servicecompany'),
    path('edit_machinemodel/<int:pk>/', MachineModelUpdateView.as_view(), name='edit_machinemodel'),
    path('edit_enginemodel/<int:pk>/', EngineModelUpdateView.as_view(), name='edit_enginemodel'),
    path('edit_transmissionmodel/<int:pk>/', TransmissionModelUpdateView.as_view(), name='edit_transmissionmodel'),
    path('edit_daxlemodel/<int:pk>/', DrivingAxleModelUpdateView.as_view(), name='create_daxlemodel'),
    path('edit_saxlemodel/<int:pk>/', SteeringAxleModelUpdateView.as_view(), name='edit_saxlemodel'),
    path('edit_maintenancetype/<int:pk>/', MaintenanceTypeUpdateView.as_view(), name='edit_maintenancetype'),
    path('edit_breakdownunit/<int:pk>/', BreakdownUnitUpdateView.as_view(), name='edit_breakdownunit'),
    path('edit_recovermethod/<int:pk>/', RecoverMethodUpdateView.as_view(), name='edit_recovermethod'),
]